messages:
  ru:
    dontHavePerm: '&cУ вас нет прав!'
    consoleCantExecuteThis: '&cНельзя запустить это из консоли!'
    noKitsAvailable: '&eНет доступных наборов'
    availableKits: '&bСписок доступных наборов: '
    kitAlreadyExists: '&cЭтот набор уже существует!'
    kitCreated: '&bНабор ''&e%kname%&b'' создан!'
    kitNotExists: '&cЭтого набора не существует!'
    kitDeleted: '&bНабор ''&e%kname%&b'' удален!'
    kitDescr: '&bНабор ''&e%kname%&b'' - перезарядка &e%cooldown%&b секунд'
    kitItemDescr: '&b  Предмет &e#%index%&b: &a%item%&b x &a%count%'
    kitCleared: '&bНабор ''&e%kname%&b'' очищен!'
    noItemInHand: '&cУ вас нет предмета в руке!'
    typeCorrectInt: '&cВведите корректное число!'
    kitSetCooldown: '&bВ наборе ''&e%kname%&b'' установлена перезарядка в &e%value%&b
      секунд'
    notEgoughSlots: '&cНедостаточно свободного места в инвентаре!'
    kitCooldown: '&cЭтот набор можно получить только через %time%'
    kitDispensed: '&bВыдан набор ''&e%kname%&b'''
    kitItemAdded: '&bВ набор ''&e%kname%&b'' добавлен предмет &e%item%'
    kitItemSet: '&bВ набор ''&e%kname%&b'' на место &e%id%&b добавлен предмет &e%item%'
    kitItemGet: '&bИз набора ''&e%kname%&b'' выдан предмет &e%item%&b под номером
      &e%id%'
    kitItemDeleted: '&bИз набора ''&e%kname%&b'' удален предмет &e%item%&b под номером
      &e%id%'
    kitHelp: '&bСправка: '
    confReloaded: '&bКонфигурационный файл перезагружен.'
    cooldownsCleared: '&bКулдаун китов обнулен.'
    unknownCommandSyntax: '&cНеверный синтаксис команды!'
  en:
    dontHavePerm: '&cYou don''t have permission!'
    consoleCantExecuteThis: '&cCan''t execute this from console!'
    noKitsAvailable: '&eList of available kits is empty.'
    availableKits: '&bList of available kits: '
    kitAlreadyExists: '&cThis kit already exists!'
    kitCreated: '&bKit ''&e%kname%&b'' created!'
    kitNotExists: '&cThis kit isn''t exists!'
    kitDeleted: '&bKit ''&e%kname%&b'' deleted!'
    kitDescr: '&bKit ''&e%kname%&b'' - &e%cooldown%&b seconds cooldown'
    kitItemDescr: '&b  Item &e#%index%&b: &a%item%&b x &a%count%'
    kitCleared: '&bKit ''&e%kname%&b'' cleared!'
    noItemInHand: '&cYou don''t have any item in hand!'
    typeCorrectInt: '&cType corrent integer!'
    kitSetCooldown: '&bIn the kit ''&e%kname%&b'' is set cooldown &e%value%&b seconds'
    notEgoughSlots: '&cNot enough free space in inventory!'
    kitCooldown: '&cYou can get this kit after %time%'
    kitDispensed: '&bIssued kit ''&e%kname%&b'''
    kitItemAdded: '&bAdded item &e%item% in kit ''&e%kname%&b'''
    kitItemSet: '&bAdded item &e%item%&b in kit ''&e%kname%&b'' on position &e%id%'
    kitItemGet: '&bIssued item &e%item%&b from kit ''&e%kname%&b'' on position &e%id%'
    kitItemDeleted: '&bRemoved item &e%item%&b in kit ''&e%kname%&b'' on position
      &e%id%'
    kitHelp: '&bHelp: '
    confReloaded: '&bConfiguration file reloaded.'
    cooldownsCleared: '&bUser cooldowns dropped.'
    unknownCommandSyntax: '&cWrong command syntax!'
kitOnFirstJoin: none
locale: en
